// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSia2025.BD;

#nullable disable

namespace ProyectoSia2025.BD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221213633_formateo")]
    partial class formateo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmpresasEmpresas", b =>
                {
                    b.Property<int>("AsociadoConmigoId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresasAsociadasId")
                        .HasColumnType("int");

                    b.HasKey("AsociadoConmigoId", "EmpresasAsociadasId");

                    b.HasIndex("EmpresasAsociadasId");

                    b.ToTable("EmpresasEmpresas");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.ContactosEmpresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoContacto")
                        .HasColumnType("int");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex(new[] { "DNI" }, "Contacto_DNI")
                        .IsUnique();

                    b.ToTable("ContactoEmpresas");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Diseños", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoPropioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPlano")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoPropioId");

                    b.HasIndex("ObraId");

                    b.ToTable("Diseños");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.EmpleadosPropios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionHogarEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpleadoPropio");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsMiEmpresa")
                        .HasColumnType("bit");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CUIT" }, "Empresa_CUIT")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.InformeInspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conclusiones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.Property<string>("RutaPdfInforme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.ToTable("InformeInspecciones");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.InspeccionRequisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cumple")
                        .HasColumnType("bit");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequisitoSeguridadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.HasIndex("RequisitoSeguridadId");

                    b.ToTable("InspeccionRequisitos");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Inspecciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpleadoPropioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estadoInspeccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoPropioId");

                    b.HasIndex("ObraId");

                    b.ToTable("Inspecciones");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.NoConformidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Corregida")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCorreccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimiteCorreccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.ToTable("NoConformidades");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Obras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresasId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoHabilitacion")
                        .HasColumnType("int");

                    b.Property<int>("EstadoObra")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimaHabilitacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoHabilitacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InformeHabilitanteId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoNoHabilitacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Presupuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresasId");

                    b.HasIndex("InformeHabilitanteId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.ObrasContactos", b =>
                {
                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("ContactoEmpresaId")
                        .HasColumnType("int");

                    b.HasKey("ObraId", "ContactoEmpresaId");

                    b.HasIndex("ContactoEmpresaId");

                    b.ToTable("ObrasContactos");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.ObrasEmpleados", b =>
                {
                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ObraId", "EmpleadoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ObrasEmpleados");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.RequisitoSeguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RequisitoSeguridades");
                });

            modelBuilder.Entity("EmpresasEmpresas", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Empresas", null)
                        .WithMany()
                        .HasForeignKey("AsociadoConmigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Empresas", null)
                        .WithMany()
                        .HasForeignKey("EmpresasAsociadasId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.ContactosEmpresas", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Empresas", "Empresa")
                        .WithMany("ContactosEmpresas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Diseños", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.EmpleadosPropios", "EmpleadoPropio")
                        .WithMany()
                        .HasForeignKey("EmpleadoPropioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Obras", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoPropio");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.EmpleadosPropios", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Empresas", "Empresa")
                        .WithMany("EmpleadosPropios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.InformeInspeccion", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Inspecciones", "Inspeccion")
                        .WithMany()
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.InspeccionRequisito", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Inspecciones", "Inspeccion")
                        .WithMany()
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.RequisitoSeguridad", "RequisitoSeguridad")
                        .WithMany()
                        .HasForeignKey("RequisitoSeguridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");

                    b.Navigation("RequisitoSeguridad");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Inspecciones", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.EmpleadosPropios", "EmpleadoPropio")
                        .WithMany()
                        .HasForeignKey("EmpleadoPropioId");

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Obras", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoPropio");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.NoConformidad", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Inspecciones", "Inspeccion")
                        .WithMany()
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Obras", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Empresas", "Empresa")
                        .WithMany("Obras")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Empresas", null)
                        .WithMany("ObrasAsociadas")
                        .HasForeignKey("EmpresasId");

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.InformeInspeccion", "InformeHabilitante")
                        .WithMany()
                        .HasForeignKey("InformeHabilitanteId");

                    b.Navigation("Empresa");

                    b.Navigation("InformeHabilitante");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.ObrasContactos", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.ContactosEmpresas", "ContactoEmpresa")
                        .WithMany("ObrasContactos")
                        .HasForeignKey("ContactoEmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Obras", "Obra")
                        .WithMany("ObrasContactos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactoEmpresa");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.ObrasEmpleados", b =>
                {
                    b.HasOne("ProyectoSia2025.BD.Data.Entities.EmpleadosPropios", "Empleado")
                        .WithMany("ObrasEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoSia2025.BD.Data.Entities.Obras", "Obra")
                        .WithMany("ObrasEmpleados")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.ContactosEmpresas", b =>
                {
                    b.Navigation("ObrasContactos");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.EmpleadosPropios", b =>
                {
                    b.Navigation("ObrasEmpleados");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Empresas", b =>
                {
                    b.Navigation("ContactosEmpresas");

                    b.Navigation("EmpleadosPropios");

                    b.Navigation("Obras");

                    b.Navigation("ObrasAsociadas");
                });

            modelBuilder.Entity("ProyectoSia2025.BD.Data.Entities.Obras", b =>
                {
                    b.Navigation("ObrasContactos");

                    b.Navigation("ObrasEmpleados");
                });
#pragma warning restore 612, 618
        }
    }
}
